// test/smoke.test.mjs — boots this canvas's runtime and exercises its actions.
// Generated by create-canvas-app, then specialized for Wiki Discover.
// Run:  node test/smoke.test.mjs
//
// Strategy: most behavior is verified DETERMINISTICALLY and OFFLINE via
// `runtime.invoke(action, input, { domainId })` + `runtime.getState(domainId)`,
// each test using its own domainId for isolation. Network paths (next_article,
// load_images) are covered by stubbing global fetch with canned Wikipedia
// payloads, so the recommender's fetch→rank→advance flow is tested without the
// network. One HTTP round-trip confirms the POST /action envelope + error codes.
import assert from "node:assert/strict";
import { mkdtemp, rm, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const home = await mkdtemp(join(tmpdir(), "wiki-discover-smoke-"));
process.env.COPILOT_HOME = home;

const { canvasConfig } = await import("../canvas.mjs");
const { createCanvasRuntime } = await import("../canvas-kit/server.mjs");
const runtime = createCanvasRuntime(canvasConfig);

let passed = 0;
async function test(label, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok  ${label}`);
  } catch (e) {
    console.error(`FAIL  ${label}\n      ${e.message}`);
    process.exitCode = 1;
    throw e;
  }
}
const inv = (action, input, domainId) => runtime.invoke(action, input, { domainId });
const st = (domainId) => runtime.getState(domainId);

// ---- deterministic fetch stub ---------------------------------------------
const realFetch = globalThis.fetch;
let stub = null;
globalThis.fetch = async (url, opts) => (stub ? stub(String(url), opts) : realFetch(url, opts));
const json = (body) => ({ ok: true, status: 200, json: async () => body });

const PAGES = {
  query: {
    pages: {
      1: { pageid: 1, title: "Galaxy", description: "astronomy galaxy", extract: "A galaxy is a system of stars.", fullurl: "https://en.wikipedia.org/wiki/Galaxy", thumbnail: { source: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Galaxy.jpg/240px-Galaxy.jpg" } },
      2: { pageid: 2, title: "Cooking", description: "food cooking", extract: "Cooking is the art of preparing food.", fullurl: "https://en.wikipedia.org/wiki/Cooking" },
      3: { pageid: 3, title: "Mercury (disambiguation)", description: "topics", extract: "Mercury may refer to.", fullurl: "https://en.wikipedia.org/wiki/Mercury", pageprops: { disambiguation: "" } },
      4: { pageid: 4, title: "Plan (disambiguation)", description: "topics", extract: "Plan may refer to.", fullurl: "https://en.wikipedia.org/wiki/Plan" },
    },
  },
};
const MEDIA = {
  items: [
    { type: "image", showInGallery: true, srcset: [{ src: "//upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pic1.jpg/500px-Pic1.jpg", scale: "1x" }], caption: { text: "Picture one" } },
    { type: "image", showInGallery: false, srcset: [{ src: "//upload.wikimedia.org/x/Hidden.jpg", scale: "1x" }] },
    { type: "video", srcset: [{ src: "//upload.wikimedia.org/x/Clip.webm", scale: "1x" }] },
  ],
};
const isMedia = (u) => u.includes("/api/rest_v1/page/media-list/");

// Deterministic article fixtures for offline rate() learning.
const ASTRO = { id: "a1", title: "Galaxy cluster", description: "astronomy cosmology", url: "https://x/1" };
const ASTRO2 = { id: "a2", title: "Astronomy basics", description: "astronomy science", url: "https://x/2" };
const POP = { id: "p1", title: "Pop singer", description: "celebrity music", url: "https://x/3" };

try {
  // ---- HTTP envelope (one round-trip proves the POST /action contract) ------
  const open = await runtime.openInstance({ instanceId: "smoke", input: {}, ctx: { instanceId: "smoke", input: {} } });
  const post = (action, input) =>
    fetch(new URL("/action", open.url), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actionName: action, input }) }).then(
      async (r) => ({ status: r.status, body: await r.json() }),
    );

  await test("opens on a loopback url", () => assert.match(open.url, /^http:\/\/127\.0\.0\.1:\d+\/$/));
  await test("POST /action returns an ok envelope", async () => {
    const { status, body } = await post("list_recommendations", {});
    assert.equal(status, 200);
    assert.equal(body.ok, true);
    assert.ok(Array.isArray(body.result.interests));
  });
  await test("POST /action maps a handler throw to 500 ok:false", async () => {
    const { status, body } = await post("set_lang", { lang: "not a code!" });
    assert.equal(status, 500);
    assert.equal(body.ok, false);
  });
  await test("POST /action maps an unknown action to 400", async () => {
    const { status, body } = await post("nope", {});
    assert.equal(status, 400);
    assert.equal(body.ok, false);
  });

  // ---- initial shape -------------------------------------------------------
  await test("initial state has the recommender shape", async () => {
    const s = await st("init");
    assert.equal(s.current, null);
    assert.deepEqual(s.queue, []);
    assert.deepEqual(s.weights, {});
    assert.deepEqual(s.interests, []);
    assert.equal(s.stats.meh, 0);
    assert.equal(s.lang, "en");
    assert.equal(s.lastRefresh, null);
  });

  // ---- feedback learning ---------------------------------------------------
  await test("rate up learns +1 weights and records history", async () => {
    const r = await inv("rate", { value: "up", article: ASTRO2 }, "learn");
    assert.ok(r.learnedFrom.includes("astronomy"));
    const s = await st("learn");
    assert.equal(s.weights.astronomy, 1);
    assert.equal(s.stats.liked, 1);
    assert.equal(s.liked.length, 1);
  });
  await test("meh is a gentle negative (−0.34), gentler than a dislike", async () => {
    await inv("rate", { value: "meh", article: ASTRO }, "learn"); // astronomy 1 → 0.66
    const s = await st("learn");
    assert.equal(s.weights.astronomy, 0.66, "1 - 0.34 = 0.66, not 0 like a dislike would be");
    assert.equal(s.stats.meh, 1);
    assert.equal(s.liked.length, 1); // meh keeps no history entry
    assert.equal(s.disliked.length, 0);
  });
  await test("rate down learns a full −1 weight", async () => {
    await inv("rate", { value: "down", article: POP }, "learn");
    const s = await st("learn");
    assert.equal(s.weights.celebrity, -1);
    assert.equal(s.stats.disliked, 1);
  });
  await test("invalid rate value is rejected", () =>
    assert.rejects(inv("rate", { value: "sideways", article: ASTRO }, "learn-bad"), /up.*meh.*down/));
  await test("rate with no current and no payload throws", () =>
    assert.rejects(inv("rate", { value: "up" }, "empty"), /No article to rate/));

  await test("weights clamp at +12 under repeated likes", async () => {
    for (let i = 0; i < 15; i++) await inv("rate", { value: "up", article: { id: "g", title: "G", description: "astronomy" } }, "clamp");
    assert.equal((await st("clamp")).weights.astronomy, 12);
  });
  await test("a weight that returns to exactly 0 is deleted", async () => {
    await inv("rate", { value: "up", article: { id: "z", title: "Z", description: "astronomy" } }, "zero"); // +1
    await inv("rate", { value: "down", article: { id: "z", title: "Z", description: "astronomy" } }, "zero"); // -1 → 0
    assert.ok(!("astronomy" in (await st("zero")).weights), "zeroed weight should be pruned");
  });
  await test("stats stay truthful when an article changes sentiment (L1)", async () => {
    const A = { id: "s1", title: "S", description: "astronomy" };
    await inv("rate", { value: "up", article: A }, "divergence");
    let s = await st("divergence");
    assert.equal(s.stats.liked, 1);
    await inv("rate", { value: "meh", article: A }, "divergence"); // moves out of liked
    s = await st("divergence");
    assert.equal(s.liked.length, 0);
    assert.equal(s.stats.liked, 0, "stats.liked must follow the history, not keep inflating");
  });

  // ---- interests -----------------------------------------------------------
  await test("add_interest adds and de-dupes (case-insensitive)", async () => {
    assert.equal((await inv("add_interest", { interest: "Astronomy" }, "ints")).added, true);
    assert.equal((await inv("add_interest", { interest: "astronomy" }, "ints")).added, false);
    assert.deepEqual((await st("ints")).interests, ["Astronomy"]);
  });
  await test("set_interests replaces the whole list (deduped, trimmed)", async () => {
    await inv("set_interests", { interests: ["Space exploration", "Jazz", "jazz", "  Rome  "] }, "ints");
    assert.deepEqual((await st("ints")).interests, ["Space exploration", "Jazz", "Rome"]);
  });
  await test("remove_interest removes a present interest", async () => {
    const r = await inv("remove_interest", { interest: "Jazz" }, "ints");
    assert.equal(r.removed, true);
    assert.deepEqual((await st("ints")).interests, ["Space exploration", "Rome"]);
  });
  await test("removing an absent interest is a no-op (L3)", async () => {
    const r = await inv("remove_interest", { interest: "not-there" }, "ints");
    assert.equal(r.removed, false);
  });
  await test("MAX_INTERESTS (40) cap is enforced", async () => {
    for (let i = 0; i < 40; i++) await inv("add_interest", { interest: `topic${i}` }, "cap");
    assert.equal((await st("cap")).interests.length, 40);
    await assert.rejects(inv("add_interest", { interest: "topic40" }, "cap"), /Too many interests/);
  });

  // ---- lang / reset / list -------------------------------------------------
  await test("set_lang switches edition, clears the pool, keeps interests + weights", async () => {
    await inv("add_interest", { interest: "Volcanoes" }, "lang");
    await inv("rate", { value: "up", article: ASTRO2 }, "lang");
    const r = await inv("set_lang", { lang: "es" }, "lang");
    assert.equal(r.lang, "es");
    const s = await st("lang");
    assert.equal(s.lang, "es");
    assert.equal(s.current, null);
    assert.deepEqual(s.queue, []);
    assert.deepEqual(s.interests, ["Volcanoes"], "interests persist across languages");
    assert.ok(s.weights.astronomy > 0, "learned weights persist across languages");
  });
  await test("reset_preferences forgets feedback but keeps interests", async () => {
    await inv("reset_preferences", {}, "lang");
    const s = await st("lang");
    assert.deepEqual(s.weights, {});
    assert.deepEqual(s.liked, []);
    assert.equal(s.stats.meh, 0);
    assert.deepEqual(s.interests, ["Volcanoes"], "interests survive a reset");
  });
  await test("list_recommendations summarizes interests + learned topics", async () => {
    await inv("add_interest", { interest: "Rome" }, "rec");
    await inv("rate", { value: "up", article: ASTRO2 }, "rec");
    const r = await inv("list_recommendations", {}, "rec");
    assert.ok(r.interests.includes("Rome"));
    assert.ok(r.learnedTopics.includes("astronomy"));
    assert.match(r.summary, /Interests:/);
  });

  // ---- persistence / backfill (#33) ----------------------------------------
  await test("loadState backfills fields missing from an older saved profile", async () => {
    const dir = join(home, "extensions", "wiki-discover", "artifacts");
    await mkdir(dir, { recursive: true });
    // Old-shape state: no `interests`, no `stats.meh`, has a legacy `skipped`.
    await writeFile(
      join(dir, "old.json"),
      JSON.stringify({ profile: "old", lang: "es", weights: { astronomy: 2 }, current: null, queue: [], liked: [], disliked: [], seenIds: [], stats: { rated: 1, liked: 1, disliked: 0, skipped: 3 }, error: null, lastRefresh: null }),
    );
    const s = await st("old");
    assert.deepEqual(s.interests, [], "interests backfilled");
    assert.equal(s.stats.meh, 0, "stats.meh backfilled");
    assert.equal(s.lang, "es", "saved fields preserved");
    assert.equal(s.weights.astronomy, 2, "saved weights preserved");
  });

  // ---- stubbed network: fetch → rank → advance flow ------------------------
  stub = (url) => (isMedia(url) ? json(MEDIA) : json(PAGES));

  await test("next_article loads a ranked pool and filters disambiguation pages", async () => {
    const r = await inv("next_article", {}, "flow");
    assert.equal(r.ok, true);
    const s = await st("flow");
    assert.ok(s.current, "an article is on screen");
    assert.equal(s.current.title, "Galaxy");
    assert.equal(s.queue.length, 1);
    assert.equal(s.queue[0].title, "Cooking");
    const titles = [s.current.title, ...s.queue.map((q) => q.title)].join("|");
    assert.doesNotMatch(titles, /disambiguation/i, "disambiguation pages must be filtered out");
    assert.ok(s.lastRefresh);
  });
  await test("removing an absent interest preserves a populated queue (L3)", async () => {
    const r = await inv("remove_interest", { interest: "nope" }, "flow");
    assert.equal(r.removed, false);
    assert.equal((await st("flow")).queue.length, 1, "queue must not be cleared on a no-op removal");
  });
  await test("rating the current article advances + re-ranks + marks it seen (M1)", async () => {
    await inv("rate", { value: "down" }, "flow"); // rate current (Galaxy)
    const s = await st("flow");
    assert.equal(s.current.title, "Cooking", "advanced to the next ranked card");
    assert.ok(s.seenIds.includes("1"), "the rated article id is now seen");
    assert.equal(s.weights.astronomy, -1, "weights updated from the rated article");
  });
  await test("load_images attaches the article's images and is idempotent (#28)", async () => {
    const r1 = await inv("load_images", {}, "flow");
    assert.equal(r1.count, 1, "one gallery image (video + non-gallery filtered out)");
    const s1 = await st("flow");
    assert.equal(s1.current.imagesLoaded, true);
    assert.equal(s1.current.images.length, 1);
    const r2 = await inv("load_images", {}, "flow"); // idempotent — no refetch
    assert.equal(r2.count, 1);
  });
  await test("skip advances without learning, then errors when nothing is left", async () => {
    await inv("skip", {}, "flow"); // skip Cooking → queue empty → current null
    const s = await st("flow");
    assert.equal(s.current, null);
    assert.ok(s.seenIds.includes("2"));
    await assert.rejects(inv("skip", {}, "flow"), /No article to skip/);
  });
  await test("a transient media-list failure flags imagesError (retryable), not imagesLoaded (L5)", async () => {
    await inv("next_article", {}, "imgerr"); // loads Galaxy via PAGES stub
    stub = (url) => {
      if (isMedia(url)) throw new Error("network down");
      return json(PAGES);
    };
    const r = await inv("load_images", {}, "imgerr");
    assert.equal(r.ok, true, "errors are swallowed — never a hard failure");
    const s = await st("imgerr");
    assert.equal(s.current.imagesError, true);
    assert.notEqual(s.current.imagesLoaded, true, "stays retryable, not marked loaded");
  });

  // ---- AI summary (host model bridge) --------------------------------------
  stub = (url) => (isMedia(url) ? json(MEDIA) : json(PAGES));
  await test("AI: request_summary marks the current article thinking and returns a prompt", async () => {
    await inv("next_article", {}, "ai"); // loads Galaxy (id "1")
    const r = await inv("request_summary", {}, "ai");
    assert.equal(r.id, "1");
    assert.match(r.prompt, /gist|summary/i);
    const s = await st("ai");
    assert.equal(s.current.aiSummaryPending, true);
  });
  await test("AI: set_summary stores the gist and clears the pending spinner", async () => {
    await inv("set_summary", { id: "1", text: "A galaxy is a vast system of stars bound by gravity." }, "ai");
    const s = await st("ai");
    assert.match(s.current.aiSummary, /galaxy/i);
    assert.equal(s.current.aiSummaryPending, false);
  });
  await test("AI: a stale set_summary (id mismatch) is ignored", async () => {
    const r = await inv("set_summary", { id: "999", text: "nope" }, "ai");
    assert.equal(r.stale, true);
  });
  await test("AI: request_summary with no current article throws no_current", async () => {
    await assert.rejects(inv("request_summary", {}, "ai-empty"), (e) => e.code === "no_current");
  });
} finally {
  globalThis.fetch = realFetch;
  await runtime.shutdown();
  await rm(home, { recursive: true, force: true });
}

console.log(`\n${passed} checks passed`);
